# Generated by Django 3.2.5 on 2021-07-09 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('text', 'Ответ текстом'), ('single_choice', 'Ответ с выбором одного варианта'), ('multiple_choice', 'Ответ с выбором нескольких вариантов')], default='text', max_length=15)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='api.question', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'question_response',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'db_table': 'survey',
            },
        ),
        migrations.CreateModel(
            name='QuestionTextResponse',
            fields=[
                ('question_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='text_response', serialize=False, to='api.questionresponse', verbose_name='Ответ текстом')),
                ('text', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Ответ текстом',
                'verbose_name_plural': 'Ответы текстом',
                'db_table': 'question_text_response',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='api.survey', verbose_name='Ответ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_response', to=settings.AUTH_USER_MODEL, verbose_name='Ответ на опрос')),
            ],
            options={
                'verbose_name': ('Ответ на опрос',),
                'verbose_name_plural': 'Ответы на опросы',
                'db_table': 'survey_response',
            },
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='survey_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_response', to='api.surveyresponse', verbose_name='Ответ на вопрос'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to=settings.AUTH_USER_MODEL, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='api.survey', verbose_name='Опрос'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='api.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'db_table': 'choice',
            },
        ),
        migrations.CreateModel(
            name='QuestionSingleChoiceResponse',
            fields=[
                ('question_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='single_choice_response', serialize=False, to='api.questionresponse', verbose_name='Ответ с выбором одного варианта')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='api.choice', verbose_name='Ответ с выбором одного варианта')),
            ],
            options={
                'verbose_name': ('Ответ с выбором одного варианта',),
                'verbose_name_plural': 'Ответы с выбором одного варианта',
                'db_table': 'question_single_choice_response',
            },
        ),
        migrations.CreateModel(
            name='QuestionMultipleChoiceResponse',
            fields=[
                ('question_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='multiple_choice_response', serialize=False, to='api.questionresponse', verbose_name='Ответ с выбором нескольких вариантов')),
                ('choices', models.ManyToManyField(related_name='responses', to='api.Choice')),
            ],
            options={
                'verbose_name': 'Ответ с выбором нескольких вариантов',
                'verbose_name_plural': 'Ответы с выбором нескольких вариантов',
                'db_table': 'question_multiple_choice_response',
            },
        ),
    ]
